// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/opam22/burgers/models"

// IOrderService is an autogenerated mock type for the IOrderService type
type IOrderService struct {
	mock.Mock
}

// MakeOrder provides a mock function with given fields: order
func (_m *IOrderService) MakeOrder(order models.Order) (models.Order, error) {
	ret := _m.Called(order)

	var r0 models.Order
	if rf, ok := ret.Get(0).(func(models.Order) models.Order); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Order) error); ok {
		r1 = rf(order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
